// Removed the unused date-fns import to resolve package installation issues

export const ISO8583Fields = [
  { field: '0', description: 'MTI', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '2', description: 'PAN', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '3', description: 'PROCESSING_CODE', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '4', description: 'AMOUNT', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '5', description: 'AMOUNT_RECONCILIATION', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '6', description: 'AMOUNT_CARDHOLDER_BILLING', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '7', description: 'TRANSMISSION_DATE_TIME', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '8', description: 'AMOUNT_CARDHOLDER_FEE', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '11', description: 'STAN', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '12', description: 'LOCAL_TIME', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '13', description: 'EFFECTIVE_DATE', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '14', description: 'EXPIRATION_DATE', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '15', description: 'SETTLEMENT_DATE', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '17', description: 'CAPTURE_DATE', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '18', description: 'MESSAGE_ERROR', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '19', description: 'ACQUIRING_COUNTRY_CODE', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '21', description: 'LIFECYCLE_DATA', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '22', description: 'POS_DATA', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '23', description: 'CARD_SEQUENCE', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '24', description: 'FUNCTION_CODE', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '25', description: 'REASON_CODE', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '26', description: 'MERCHANT_CATEGORY', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '27', description: 'POS_CAPABILITIES', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '30', description: 'AMOUNTS_ORIGINAL', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '32', description: 'ACQUIRER_ID', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '33', description: 'FORWARDING_ID', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '35', description: 'TRACK2', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '37', description: 'RRN', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '38', description: 'APPROVAL_CODE', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '39', description: 'RESPONSE_CODE', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '41', description: 'TERMINAL_ID', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '42', description: 'MERCHANT_ID', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '43', description: 'CARD_ACCEPTOR', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '45', description: 'TRACK1', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '46', description: 'FEES', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '49', description: 'VERIFICATION_DATA', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '52', description: 'PIN_BLOCK', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '53', description: 'SECURITY_INFO', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '54', description: 'ADDITIONAL_AMOUNTS', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '55', description: 'ICC_DATA', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '56', description: 'ORIGINAL_DATA', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '59', description: 'TRANSPORT_DATA', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '63', description: 'DISPLAY_MESSAGE', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '68', description: 'BATCH_NUMBER', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '69', description: 'BATCH_DATA', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '72', description: 'DATA_RECORD', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '74', description: 'RECONCILIATION_DATA', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '93', description: 'DESTINATION_INSTITUTION', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '94', description: 'ORIGINATOR_INSTITUTION', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '95', description: 'REPLACEMENT_AMOUNTS', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '97', description: 'NET_RECONCILIATION', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '99', description: 'SETTLEMENT_INSTITUTION', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '100', description: 'RECEIVING_INSTITUTION', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '101', description: 'FILE_NAME', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '102', description: 'ACCOUNT_1', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '103', description: 'ACCOUNT_2', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '111', description: 'HANDBACK_DATA', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '112', description: 'TRANSPORT_DATA_ADDITIONAL', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
  { field: '113', description: 'TPP_DATA', color: 'border-l-2 border-l-gray-400', box: 'bg-gray-400', text: 'text-gray-400' },
];

export const AccountType = {
  '00': 'Default Account',
  '10': 'Savings Account',
  '20': 'Current Account',
  '30': 'Credit Account',
};

export const ISO3ResponseCode = [
  // Approval Codes (0000-0999) - Green
  { code: '0000', description: 'TRANSACTION_APPROVED', color: 'border-l-2 border-l-green-600', box: 'bg-green-600', text: 'text-green-600' },
  { code: '0001', description: 'HONOR_WITH_IDENTIFICATION', color: 'border-l-2 border-l-green-500', box: 'bg-green-500', text: 'text-green-500' },
  { code: '0002', description: 'APPROVED_PARTIAL_AMOUNT', color: 'border-l-2 border-l-green-500', box: 'bg-green-500', text: 'text-green-500' },
  { code: '0003', description: 'APPROVED_VIP', color: 'border-l-2 border-l-green-500', box: 'bg-green-500', text: 'text-green-500' },
  { code: '0004', description: 'APPROVED_PURCHASE_NOT_CASHBACK', color: 'border-l-2 border-l-green-500', box: 'bg-green-500', text: 'text-green-500' },

  // Decline Codes (1000-1999) - Red
  { code: '1001', description: 'CARD_EXPIRED', color: 'border-l-2 border-l-red-600', box: 'bg-red-600', text: 'text-red-600' },
  { code: '1002', description: 'CARD_SUSPICIOUS', color: 'border-l-2 border-l-red-600', box: 'bg-red-600', text: 'text-red-600' },
  { code: '1003', description: 'CONTACT_ACQUIRER', color: 'border-l-2 border-l-red-500', box: 'bg-red-500', text: 'text-red-500' },
  { code: '1004', description: 'RESTRICTED_CARD', color: 'border-l-2 border-l-red-600', box: 'bg-red-600', text: 'text-red-600' },
  { code: '1005', description: 'CONTACT_ACQUIRER_SECURITY', color: 'border-l-2 border-l-red-500', box: 'bg-red-500', text: 'text-red-500' },
  { code: '1006', description: 'ALLOWABLE_PIN_TRIES_EXCEEDED', color: 'border-l-2 border-l-red-600', box: 'bg-red-600', text: 'text-red-600' },
  { code: '1007', description: 'REFER_TO_CARD_ISSUER', color: 'border-l-2 border-l-red-500', box: 'bg-red-500', text: 'text-red-500' },
  { code: '1008', description: 'REFER_TO_CARD_ISSUER_SPECIAL', color: 'border-l-2 border-l-red-500', box: 'bg-red-500', text: 'text-red-500' },
  { code: '1009', description: 'INVALID_CARD_ACCEPTOR', color: 'border-l-2 border-l-red-600', box: 'bg-red-600', text: 'text-red-600' },
  { code: '1011', description: 'INVALID_CARD_NUMBER', color: 'border-l-2 border-l-red-600', box: 'bg-red-600', text: 'text-red-600' },
  { code: '1012', description: 'PIN_DATA_REQUIRED', color: 'border-l-2 border-l-red-500', box: 'bg-red-500', text: 'text-red-500' },
  { code: '1013', description: 'UNACCEPTABLE_FEE', color: 'border-l-2 border-l-red-500', box: 'bg-red-500', text: 'text-red-500' },
  { code: '1014', description: 'NO_ACCOUNT_TYPE_REQUESTED', color: 'border-l-2 border-l-red-500', box: 'bg-red-500', text: 'text-red-500' },
  { code: '1015', description: 'REQUESTED_FUNCTION_NOT_SUPPORTED', color: 'border-l-2 border-l-red-500', box: 'bg-red-500', text: 'text-red-500' },
  { code: '1016', description: 'NOT_SUFFICIENT_FUNDS', color: 'border-l-2 border-l-red-600', box: 'bg-red-600', text: 'text-red-600' },
  { code: '1017', description: 'INCORRECT_PIN', color: 'border-l-2 border-l-red-600', box: 'bg-red-600', text: 'text-red-600' },
  { code: '1018', description: 'PREVIOUSLY_REVERSED', color: 'border-l-2 border-l-red-500', box: 'bg-red-500', text: 'text-red-500' },
  { code: '1019', description: 'FURTHER_ACTIVITY_PREVENTS_REVERSAL', color: 'border-l-2 border-l-red-500', box: 'bg-red-500', text: 'text-red-500' },
  { code: '1020', description: 'FURTHER_ACTIVITY_PREVENTS_VOID', color: 'border-l-2 border-l-red-500', box: 'bg-red-500', text: 'text-red-500' },
  { code: '1021', description: 'ORIGINAL_TRANSACTION_VOIDED', color: 'border-l-2 border-l-red-500', box: 'bg-red-500', text: 'text-red-500' },

  // System Error Codes (1800-1899) - Amber/Yellow
  { code: '1802', description: 'MISSING_FIELDS', color: 'border-l-2 border-l-amber-500', box: 'bg-amber-500', text: 'text-amber-500' },
  { code: '1803', description: 'EXTRA_FIELDS_EXIST', color: 'border-l-2 border-l-amber-500', box: 'bg-amber-500', text: 'text-amber-500' },
  { code: '1804', description: 'INVALID_CARD_NUMBER_1804', color: 'border-l-2 border-l-amber-600', box: 'bg-amber-600', text: 'text-amber-600' },
  { code: '1806', description: 'CARD_NOT_ACTIVE', color: 'border-l-2 border-l-amber-600', box: 'bg-amber-600', text: 'text-amber-600' },
  { code: '1808', description: 'CARD_NOT_CONFIGURED', color: 'border-l-2 border-l-amber-600', box: 'bg-amber-600', text: 'text-amber-600' },
  { code: '1810', description: 'INVALID_AMOUNT', color: 'border-l-2 border-l-amber-600', box: 'bg-amber-600', text: 'text-amber-600' },
  { code: '1811', description: 'SYSTEM_ERROR_DATABASE', color: 'border-l-2 border-l-amber-500', box: 'bg-amber-500', text: 'text-amber-500' },
  { code: '1812', description: 'SYSTEM_ERROR_TRANSACTION', color: 'border-l-2 border-l-amber-500', box: 'bg-amber-500', text: 'text-amber-500' },
  { code: '1813', description: 'CARDHOLDER_NOT_ACTIVE', color: 'border-l-2 border-l-amber-600', box: 'bg-amber-600', text: 'text-amber-600' },
  { code: '1814', description: 'CARDHOLDER_NOT_CONFIGURED', color: 'border-l-2 border-l-amber-600', box: 'bg-amber-600', text: 'text-amber-600' },
  { code: '1815', description: 'CARDHOLDER_EXPIRED', color: 'border-l-2 border-l-amber-600', box: 'bg-amber-600', text: 'text-amber-600' },
  { code: '1816', description: 'ORIGINAL_NOT_FOUND', color: 'border-l-2 border-l-amber-500', box: 'bg-amber-500', text: 'text-amber-500' },
  { code: '1817', description: 'USAGE_LIMIT_REACHED', color: 'border-l-2 border-l-amber-600', box: 'bg-amber-600', text: 'text-amber-600' },
  { code: '1818', description: 'CONFIGURATION_ERROR', color: 'border-l-2 border-l-amber-500', box: 'bg-amber-500', text: 'text-amber-500' },
  { code: '1819', description: 'INVALID_TERMINAL', color: 'border-l-2 border-l-amber-600', box: 'bg-amber-600', text: 'text-amber-600' },
  { code: '1820', description: 'INACTIVE_TERMINAL', color: 'border-l-2 border-l-amber-600', box: 'bg-amber-600', text: 'text-amber-600' },
  { code: '1821', description: 'INVALID_MERCHANT', color: 'border-l-2 border-l-amber-600', box: 'bg-amber-600', text: 'text-amber-600' },
  { code: '1822', description: 'DUPLICATE_ENTITY', color: 'border-l-2 border-l-amber-500', box: 'bg-amber-500', text: 'text-amber-500' },
  { code: '1823', description: 'INVALID_ACQUIRER', color: 'border-l-2 border-l-amber-600', box: 'bg-amber-600', text: 'text-amber-600' },

  // Other Codes - Purple
  { code: '9102', description: 'INVALID_TRANSACTION', color: 'border-l-2 border-l-purple-600', box: 'bg-purple-600', text: 'text-purple-600' },
];

export const PosEntryMode: Record<string, { code: string; description: string; meaning: string }> = {
  '01': { code: '01', description: 'MANUAL', meaning: 'Manual entry (e.g., keyed by cashier)' },
  '02': { code: '02', description: 'MAGSTRIPE', meaning: 'Magnetic stripe read (track data read)' },
  '05': { code: '05', description: 'ICC', meaning: 'Integrated Circuit Card (ICC) read – chip card' },
  '07': { code: '07', description: 'CONTACTLESS_CHIP', meaning: 'Contactless chip read via NFC' },
  '08': { code: '08', description: 'CONTACTLESS_MAGSTRIPE', meaning: 'Contactless magnetic stripe emulation' },
  '09': { code: '09', description: 'QR_BARCODE', meaning: 'QR code read' },
  '10': { code: '10', description: 'CREDENTIAL_ON_FILE', meaning: 'Credential on file (e.g., PIN, PINless)' },
  '79': { code: '79', description: 'FALLBACK_MANUAL', meaning: 'Fallback to manual entry' },
  '80': { code: '80', description: 'FALLBACK_MAGSTRIPE', meaning: 'Fallback to magnetic stripe read' },
  '81': { code: '81', description: 'FALLBACK_MANUAL_AFTER_MAG', meaning: 'Fallback to manual entry after magnetic stripe read' },
  '90': { code: '90', description: 'MOBILE_REMOTE', meaning: 'Mobile remote' },
  '91': { code: '91', description: 'ECOMMERCE', meaning: 'E-commerce' },
  '95': { code: '95', description: 'CHIP_FAIL_CONTACTLESS', meaning: 'Contactless chip read failed' },
};

export const serviceCodes = [
  { code: '101', interchange: 'International interchange OK', authorization: 'Normal', restrictions: 'No cash advance' },
  { code: '201', interchange: 'International interchange, use only chip', authorization: 'Normal', restrictions: 'No cash advance' },
  { code: '220', interchange: 'International interchange, use only chip', authorization: 'Contact chip required', restrictions: 'No restrictions' },
  { code: '221', interchange: 'International interchange, use only chip', authorization: 'Contact chip required', restrictions: 'No cash advance' },
  { code: '601', interchange: 'National interchange, use only chip', authorization: 'Normal', restrictions: 'No cash advance' },
  { code: '721', interchange: 'Private (closed loop)', authorization: 'Normal', restrictions: 'No cash advance' },
];

export const PosConditionCode: Record<string, { code: string; description: string; meaning: string }> = {
  '00': { code: '00', description: 'NORMAL_PRESENTMENT', meaning: 'Normal presentment (face-to-face)' },
  '01': { code: '01', description: 'CUSTOMER_NOT_PRESENT', meaning: 'Customer not present (e.g., mail/phone)' },
  '02': { code: '02', description: 'STANDING_ORDER', meaning: 'Recurring billing (standing order)' },
  '03': { code: '03', description: 'CARD_NOT_PRESENT_AT_TERMINAL', meaning: 'Card not present at terminal' },
  '04': { code: '04', description: 'CARD_PRESENT_UNUSUAL', meaning: 'Card present, but unusual' },
  '05': { code: '05', description: 'TERMINAL_NOT_USED', meaning: 'Terminal not used' },
  '06': { code: '06', description: 'ECOMMERCE', meaning: 'E-commerce' },
  '07': { code: '07', description: 'ECOMMERCE_AUTHENTICATED', meaning: 'E-commerce, authenticated' },
  '08': { code: '08', description: 'MAIL_ORDER', meaning: 'Mail order' },
  '09': { code: '09', description: 'TELEPHONE_ORDER', meaning: 'Telephone order' },
  '10': { code: '10', description: 'SECURE_ECOMMERCE', meaning: 'Secure e-commerce' },
  '11': { code: '11', description: 'ACCOUNT_VERIFICATION', meaning: 'Account verification (no charge)' },
  '20': { code: '20', description: 'DELAYED_PRESENTMENT', meaning: 'Delayed presentment (batch)' },
  '60': { code: '60', description: 'SELF_SERVICE', meaning: 'In-store self-service / unattended' },
  '90': { code: '90', description: 'TEST_TRANSACTION', meaning: 'Test transaction' },
};